language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"

install:
  - composer install --no-dev

after_script:
  - wget http://fresh.packagist.jp/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml
