language: php
php:
  - nightly
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
  - hhvm

install:
    - composer install --no-dev

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover clover.xml
