language: php
sudo: false
php:
  - "7.0.0RC1"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"

install:
  - composer install --no-dev

after_script:
  - wget http://packagist.jp/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml
