<!DOCTYPE html>
<html lang="ja">
<head>
<?php
$meta['charset'] = 'UTF-8';
$meta['property']['og:title'] = 'example 07';
$meta['property']['og:description'] = 'example template';
$meta['property']['og:image'] = (array)$meta['property']['og:image'];
$meta['property']['og:image'][] = 'http://example.com/img2.jpg';
$meta['name']['twitter:title'] = 'example 07';
$this->meta = $meta;
?>
<?php echo $this->meta($meta) ?> 
 <title>example template</title>
</head>
<body>
<?php echo $this->content() ?>
</body>
</html>
